version: "3"
services:
  test:
    image: kur8/dashboard
    container_name: 'kur8-test'
    ports:
      - '8080:8080'
    volumes: 
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run test
volumes: 
  node_modules:
  